name: Test Server CI

on:
  push:
    branches: [dev]
    paths:
      - 'server/**' # Only trigger if changes are made inside the server folder
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      -  name: Install server dependencies    
         run: npm install --prefix server

      - name: Install and start Redis
        run: |
          sudo apt-get update
          sudo apt-get install redis-server -y
          sudo systemctl start redis

      - name: Test server
        env:
          SECRET: KGGL>HKHVHKWKBKJKJLMNOPKFGHN@$MGTH
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          npm test --prefix server
